/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	go: [{ type: 'autogenerated', dirName: 'go' }],
	csharp: [
		{
			type: 'autogenerated',
			dirName: 'csharp',
		},
	],
	php: [
		{
			type: 'autogenerated',
			dirName: 'php',
		},
	],
	security: [
		{
			type: 'autogenerated',
			dirName: 'security',
		},
	],
	typescript: [
		{
			type: 'autogenerated',
			dirName: 'typescript',
		},
	],
	bp: [
		{
			type: 'autogenerated',
			dirName: 'bp',
		},
	],
}

module.exports = sidebars
